FROM maven:amazoncorretto
WORKDIR /eureka-server
COPY ./ ./
RUN mvn clean install

FROM amazoncorretto:11
WORKDIR /eureka-server
COPY --from=0 /eureka-server/target/eureka-0.0.1-SNAPSHOT.jar ./
CMD ["java","-jar", "eureka-0.0.1-SNAPSHOT.jar"]